### ISSUE TITLE
undefinded method strip!

### ISSUE THREAD

**Issue by tttp** [midwire/tr4n5l4te#1]
Hi,

(tiny point: the doc doesn't mention the need to have phantomjs installed)

when running

     ./exe/translate -y ../myapp/app/locale/en.yml -l "French"

I get 

Starting Tr4n5l4te v0.1.2 @11:53:23.427
/usr/src/tr4n5l4te/lib/tr4n5l4te/translator.rb:16:in `translate': undefined method `strip!' for true:TrueClass (NoMethodError)
	from /usr/src/tr4n5l4te/lib/tr4n5l4te/runner.rb:44:in `translate'
	from /usr/src/tr4n5l4te/lib/tr4n5l4te/runner.rb:36:in `block in process'
	from /usr/src/tr4n5l4te/lib/tr4n5l4te/runner.rb:34:in `each'
	from /usr/src/tr4n5l4te/lib/tr4n5l4te/runner.rb:34:in `each_with_object'
	from /usr/src/tr4n5l4te/lib/tr4n5l4te/runner.rb:34:in `process'
	from /usr/src/tr4n5l4te/lib/tr4n5l4te/runner.rb:36:in `block in process'
	from /usr/src/tr4n5l4te/lib/tr4n5l4te/runner.rb:34:in `each'
	from /usr/src/tr4n5l4te/lib/tr4n5l4te/runner.rb:34:in `each_with_object'
	from /usr/src/tr4n5l4te/lib/tr4n5l4te/runner.rb:34:in `process'
	from /usr/src/tr4n5l4te/lib/tr4n5l4te/runner.rb:36:in `block in process'
	from /usr/src/tr4n5l4te/lib/tr4n5l4te/runner.rb:34:in `each'
	from /usr/src/tr4n5l4te/lib/tr4n5l4te/runner.rb:34:in `each_with_object'
	from /usr/src/tr4n5l4te/lib/tr4n5l4te/runner.rb:34:in `process'
	from /usr/src/tr4n5l4te/lib/tr4n5l4te/runner.rb:25:in `run'
	from ./exe/translate:9:in `<main>'

Any idea? wrong ruby version I have?
ruby-2.0.0

**Comment by midwire** [comment]
Hey, thanks for reporting this. I've been playing with phantomjs for so long i forgot it was a requirement. I'll add that to the docs.

Regarding the error, it appears that somehow a boolean is being passed into the Translator instead of a string. I'm looking into it now.

**Comment by midwire** [comment]
Would you mind posting your `.yml` file? If not, no worries. I'll try to write some specs to address it.

**Comment by midwire** [comment]
I'm wondering if you have some ERB code in your `.yml` file. This commit: 3f82278 should make it more clear.

**Comment by tttp** [comment]
I don't have any ERB, put potentially some fubar on the yml, I'm git pulling now and checking, will mail you the yml if it still fails

**Comment by midwire** [comment]
Closing this. Let me know if it is still a problem.
