### ISSUE TITLE
SSL handshake failed

### ISSUE THREAD

**Issue by gahia** [midwire/tr4n5l4te#24]
Hi! 

I got this issue, always: 

`Request to 'https://translate.google.com..  failed to reach server, check DNS and/or server status (Capybara::Poltergeist::StatusFailError)
`

It seems a PhantomJS v2+ issue. When debugging it you get:

`[DEBUG] Network - Resource request error: 6 ( "SSL handshake failed" )`

Adding `--ssl-protocol=any` to the `phantomjs_options` fix the issue. Some recommend to add too `'--ssl-protocol=tlsv1'` but so far I didn't need to explicitly add it.

For reference read: https://github.com/ariya/phantomjs/issues/12440

Using:

- Tr4n5l4te v0.1.13
- PhantomJS v2.1.1
- Ubuntu v20.04

Maybe related to #19

**Comment by midwire** [comment]
Thanks @gahia. I'll keep an eye on the issue over at phantomjs.  In the meantime I am willing to add `--ssl-protocol=tlsv1` to the options as a workaround.

**Comment by midwire** [comment]
Just noticed the PR. Thanks for that!  I'll close this then. Feel free to re-open if necessary.
