### ISSUE TITLE
Writing file

### ISSUE THREAD

**Issue by byzg** [midwire/tr4n5l4te#3]
At now if I translate to franch
```
$ bundle exec translate -y config/locales/pricing_mailer.en.yml -l "French" --verbose
```
 it is writes to *fr.yml*. In my mind it is more usefull to write to *pricing_mailer.fr.yml* in these cases cause  I can already have *fr.yml* and dont want to rewrite it

**Comment by midwire** [comment]
@byzg fixed. Thanks for the suggestion.
