### ISSUE TITLE
midwire_common causes ArgumentError

### ISSUE THREAD

**Issue by corselia** [midwire/tr4n5l4te#7]
### Expected Behavior
- No ArgumentError
- not `expected 0`

### Actual Behavior
- as below

```
ArgumentError: wrong number of arguments (given 1, expected 0) from /home/foo/bar/vendor/bundle/ruby/2.5.0/gems/midwire_common-0.3.0/lib/midwire_common/string.rb:125:in `camelize'
```

### Steps to reproduce the problem
yeah, this is a rear case, I see.

With [Legato](https://github.com/tpitale/legato) which supports Google Analytics API gem, I tried to get `Legato::Model` object and the error occured.

so as the error message I commented out as below in `midwire_common` gem.

l25 of `lib/midwire_common/string.rb` 
```ruby
  # rubocop:disable Style/PerlBackrefs
  # def camelize
    # gsub(/\/(.?)/) { '::' + $1.upcase }.gsub(/(^|_)(.)/) { $2.upcase }
  # end
```

---
* Current Version:
- Ruby 2.5.1
- Rails 5.2.0
- `midwire_common` is the all of following versions
    - 0.3.0
    - 1.1.0
    - 1.1.1

* Operating System:
- Ubuntu 16.04 LTS

thank you for useful gem :)

**Comment by Qwertie-** [comment]
Ran in to this same issue. midwire_common seems to define a bunch of methods on string. Looks like it would be advisable to not add this gem to your gemfile but instead install it outside using gem and using it just to translate yml files.

**Comment by midwire** [comment]
I removed the use of that String class. Sorry it took so long.
