### ISSUE TITLE
Google Translate now returns two matching elements for .tlid-translation (Capybara::Ambiguous)

### ISSUE THREAD

**Issue by aseroff** [midwire/tr4n5l4te#9]
### Expected Behavior

Translation succeeds

### Actual Behavior

If a translation is for a short word with masculine/feminine endings (e.g. "Friends" in "es"), Google returns two elements, one for each version. Copybara raises an exception and aborts the translation.

### Steps to reproduce the problem

Sample strings that now fail on Spanish translation: "Us", "Friends".

I'd advocate for rescuing these exceptions and just outputting the original word with warning.

---
* Current Version: 2.18
* Operating System: mac

**Comment by midwire** [comment]
Thanks @aseroff. This commit addresses multiple translations for a given word: https://github.com/midwire/tr4n5l4te/commit/081ec76da1aeeae7025e447f34b1142479281768  I think it would be nice to have a command line switch to choose masculine or feminine when those occur but I'm just not sure if that will be enough as there maybe other types of ambiguity.  If you have a better idea on how to actually translate these types of words automatically by choosing one or the other from multiples, please let me know.  For now it does what you suggested and returns the original word in the original language but prints out a warning.

**Comment by midwire** [comment]
Gem version 0.1.8 is now live with this change.

**Comment by aseroff** [comment]
Awesome! Thank you for the quick fix.
